version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: aiohttp_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  postgres:
    image: postgres:10
    container_name: aiohttp_postgres
    volumes:
      - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'
      - 'dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432

  aiohttp:
    image: test-aiohttp
    container_name: aiohttp
    ports:
      - '80:8080'
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  dbdata:
