version: '3.2'

services:
  resurface:
    image: docker.resurface.io/release/pilot:2.1.24
    container_name: hackernews_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  postgres:
    image: postgres:10
    container_name: hackernews_postgres
    volumes:
      - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'
      - 'dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432

  hackernews:
    image: test-aiohttp-hackernews
    container_name: hackernews
    command: gunicorn hackernews.app:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - '80:8080'
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  dbdata:
